# 开发环境配置
springdoc:
  paths-to-match: /**
  swagger-ui:
    operations-sorter: alpha


spring:
  mail:
    host: smtp.163.com
    username: maplechenx@163.com
    password: IADEWGWLLANKMJGJ
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
  datasource:
    ds1:
      url: jdbc:mysql://localhost:3306/forum
      username: root
      password: 111111
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        pool-name: MySQLHikariPool
    ds2:
      url: jdbc:postgresql://localhost:5432/tfidf
      username: postgres
      password: 111111
      driver-class-name: org.postgresql.Driver
      hikari:
        pool-name: PostgresHikariPool

  security:
    jwt:
      key: 'MapleChenX'
      expire: 72
      limit:
        base: 10
        upgrade: 300
        frequency: 30
    filter:
      order: -100
  web:
    verify:
      mail-limit: 60
    flow:
      period: 300
      limit: 500
      block: 1
    cors:
      origin: '*'
      credentials: false
      methods: 'GET, POST'
  minio:
    endpoint: 'http://localhost:9000'
    username: 'minioadmin'
    password: 'minioadmin'
  weather:
    key: 16eb85939a3249589fce78da9a93c3fa
